Merging upstream version 0.3.6.2.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -882,6 +882,8 @@ USE_HAL_TRUE
 USE_HAL_FALSE
 FAM_CFLAGS
 FAM_LIBS
+DESKTOP_INTEGRATION_TRUE
+DESKTOP_INTEGRATION_FALSE
 GETTEXT_PACKAGE
 USE_NLS
 MSGFMT
@@ -1516,6 +1518,8 @@ Optional Features:
   --disable-superuser-checks
                           disable checks running as super user (useful to
                           LiveCD or embedded) (default: enable)
+  --disable-desktop-integration
+                          disable desktop integrations such as icons
 
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
@@ -2308,7 +2312,7 @@ fi
 
 # Define the identity of the package.
  PACKAGE=pcmanfm
- VERSION=0.3.6.1
+ VERSION=0.3.6.2
 
 
 cat >>confdefs.h <<_ACEOF
@@ -5243,7 +5247,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 5246 "configure"' > conftest.$ac_ext
+  echo '#line 5250 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -7980,11 +7984,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7983: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7987: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7987: \$? = $ac_status" >&5
+   echo "$as_me:7991: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -8270,11 +8274,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8273: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8277: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:8277: \$? = $ac_status" >&5
+   echo "$as_me:8281: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -8374,11 +8378,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8377: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8381: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:8381: \$? = $ac_status" >&5
+   echo "$as_me:8385: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -10736,7 +10740,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10739 "configure"
+#line 10743 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -10836,7 +10840,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10839 "configure"
+#line 10843 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -13256,11 +13260,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13259: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13263: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:13263: \$? = $ac_status" >&5
+   echo "$as_me:13267: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -13360,11 +13364,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13363: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13367: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:13367: \$? = $ac_status" >&5
+   echo "$as_me:13371: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -14937,11 +14941,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14940: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14944: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:14944: \$? = $ac_status" >&5
+   echo "$as_me:14948: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -15041,11 +15045,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15044: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15048: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:15048: \$? = $ac_status" >&5
+   echo "$as_me:15052: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -17241,11 +17245,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17244: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17248: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:17248: \$? = $ac_status" >&5
+   echo "$as_me:17252: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -17531,11 +17535,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17534: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17538: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:17538: \$? = $ac_status" >&5
+   echo "$as_me:17542: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -17635,11 +17639,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17638: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17642: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:17642: \$? = $ac_status" >&5
+   echo "$as_me:17646: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -22458,6 +22462,31 @@ if test ! -z "$preferable_sudo"; then
   CPPFLAGS="$CPPFLAGS -DPREFERABLE_SUDO_PROG=\\\"$preferable_sudo\\\""
 fi
 
+# Check whether --enable-desktop-integration was given.
+if test "${enable_desktop_integration+set}" = set; then
+  enableval=$enable_desktop_integration; desktop_integration=$enableval
+else
+  desktop_integration="yes"
+fi
+
+if test x"$desktop_integration" = "xyes"; then
+
+cat >>confdefs.h <<\_ACEOF
+#define DESKTOP_INTEGRATION 1
+_ACEOF
+
+fi
+ if test "$desktop_integration" = "yes"; then
+  DESKTOP_INTEGRATION_TRUE=
+  DESKTOP_INTEGRATION_FALSE='#'
+else
+  DESKTOP_INTEGRATION_TRUE='#'
+  DESKTOP_INTEGRATION_FALSE=
+fi
+
+
+CPPFLAGS="$CPPFLAGS -fstrict-aliasing -fmessage-length=0"
+
 { echo "$as_me:$LINENO: checking for euidaccess" >&5
 echo $ECHO_N "checking for euidaccess... $ECHO_C" >&6; }
 if test "${ac_cv_func_euidaccess+set}" = set; then
@@ -22735,7 +22764,7 @@ cat >>confdefs.h <<_ACEOF
 _ACEOF
 
 
-ALL_LINGUAS="zh_TW zh_CN hu fr pl it es de sv_SE ru pt_BR ca tr eu ja pt_PT ur"
+ALL_LINGUAS="zh_TW zh_CN hu fr pl it es de sv_SE ru pt_BR ca tr eu ja pt_PT ur da no"
 
 
 for ac_header in locale.h
@@ -24400,6 +24429,13 @@ echo "$as_me: error: conditional \"USE_HAL\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
+if test -z "${DESKTOP_INTEGRATION_TRUE}" && test -z "${DESKTOP_INTEGRATION_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"DESKTOP_INTEGRATION\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"DESKTOP_INTEGRATION\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
@@ -25093,6 +25129,8 @@ USE_HAL_TRUE!$USE_HAL_TRUE$ac_delim
 USE_HAL_FALSE!$USE_HAL_FALSE$ac_delim
 FAM_CFLAGS!$FAM_CFLAGS$ac_delim
 FAM_LIBS!$FAM_LIBS$ac_delim
+DESKTOP_INTEGRATION_TRUE!$DESKTOP_INTEGRATION_TRUE$ac_delim
+DESKTOP_INTEGRATION_FALSE!$DESKTOP_INTEGRATION_FALSE$ac_delim
 GETTEXT_PACKAGE!$GETTEXT_PACKAGE$ac_delim
 USE_NLS!$USE_NLS$ac_delim
 MSGFMT!$MSGFMT$ac_delim
@@ -25114,7 +25152,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 37; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 39; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
